baseURL = "https://gileshutton.com/"
languageCode = "en-us"
title = "Giles"
theme = "jane"

paginate = 3
rssLimit = 20
googleAnalytics = ""

[author]
  name = "Giles Hutton"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Tags"
  weight = 20
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "Categories"
  weight = 30
  identifier = "categories"
  url = "/categories/"
[[menu.main]]
  name = "Archives"
  weight = 40
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "About"
  weight = 50
  identifier = "about"
  url = "/about/"

[params]
  since = "2019"
  homeFullContent = false
  rssFullContent = true

  logoTitle = "On Writing"
  dateFormatToUse = "2006-01-02"
  keywords = ["Giles", "Hutton", "Writing"]

[params.social]
    a-email = "mailto:hutton.giles+web@gmail.com"
    g-github = "http://github.com/Stringy/"
    o-goodreads = "https://www.goodreads.com/user/show/91307502-giles-hutton"
