baseURL = "https://gileshutton.com"
title = "Giles Hutton"
theme = "m10c"
paginate = 10

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
identifier = "code"
name = "Code"
url = "/coding"
[[menu.main]]
identifier = "writing"
name = "Writing"
url = "/writing"
[[menu.main]]
identifier = "reviews"
name = "Reviews"
url = "/reviews"
[[menu.main]]
identifier = "about"
name = "About"
url = "/about"

[params]
author = "Giles Hutton"
description = "Programming and Writing of things."
favicon = "/favicon/favicon.ico"
avatar = "avatar.png"

[[params.social]]
icon = "github"
name = "Github"
url = "https://github.com/stringy/"

# Red theme
[params.style]
darkestColor = "#284982"
darkColor = "#212121"
lightColor = "#d6d6d6"
lightestColor = "#d3d3d3"
primaryColor = "#ffffff"
